---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: backup-server
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: backup-network

  - name: minio
    image: minio/minio:latest
    pre_build_image: true
    command: server /data --console-address ":9001"
    env:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    published_ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - name: backup-network

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      backup-server:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

scenario:
  name: s3
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
